dist: focal
git:
  depth: false
  submodules: false
language: python
python:
  - "3.9"

addons:
  apt:
    packages:
      - console-data
      - cppcheck
      - libsystemd-dev

script:
  - set -e
  - scripts/install_python_dependencies.sh
  - make

after_success:
  - poetry run coveralls

before_deploy:
  - pip install cloudsmith-cli
